import { ArracadasInterface } from "./arracadas";

export const ARRACADASconst: ArracadasInterface[]=[

    {   
        id:1,
        titulo: "Arracadas arcoiris",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'arcoiris.jpg',
        precio:150,
    },    
    {   
        id:2,
        titulo: "Arracadas colores",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'azul-azulfuerte-rosa.jpg',
        precio:150,
    },    
    {   
        id:3,
        titulo: "Arracadas azul cielo",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'azul-cielo.jpg',
        precio:130,
    },    
    {   
        id:4,
        titulo: "Arracadas azules",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'azul-transparente.jpg',
        precio:130,
    },    
    {   
        id:5,
        titulo: "Arracadas blancas",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'blancas.jpg',
        precio:130,
    },    
    {   
        id:6,
        titulo: "Arracadas de colores",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'blanco-azul-rosa.jpg',
        precio:150,
    },    
    {   
        id:7,
        titulo: "Arracadas de colores",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'colores-1.jpg',
        precio:130,
    },    
    {   
        id:8,
        titulo: "Arracadas de colores",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'colores-2.jpg',
        precio:150,
    },    
    {   
        id:9,
        titulo: "Arracadas de colores",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'colores-transparente.jpg',
        precio:150,
    },
    {   
        id:10,
        titulo: "Arracadas doradas",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'doradas.jpg',
        precio:130,
    }, 
    {   
        id:11,
        titulo: "Arracadas lilas",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'lila-transparente.jpg',
        precio:130,
    }, 
    {   
        id:12,
        titulo: "Arracadas lilas",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'lila.jpg',
        precio:130,
    }, 
    {   
        id:13,
        titulo: "Arracadas negras",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'negras.jpg',
        precio:130,
    }, 
    {   
        id:14,
        titulo: "Arracadas rojas",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'rojas.jpg',
        precio:130,
    }, 
    {   
        id:15,
        titulo: "Arracadas rosas",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'rosas.jpg',
        precio:130,
    }, 
    {   
        id:16,
        titulo: "Arracadas de colores",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'verde-azul-rosa.jpg',
        precio:150,
    }, 
    {   
        id:17,
        titulo: "Arracadas verdes",
        descripcion: "Estas arracadas están hechas a mano con chaquira en todos vibrantes que representan amor, diversidad y buena energía. Perfectas para darle un toque único y lleno de vida a tu outfit.",
        img: 'verdes.jpg',
        precio:130,
    }, 
]